version: "3.4"

services:
  ui:
    # image: ${DOCKER_USER}/ui:latest
    container_name: ui
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:80
    restart: always
    environment:
      - REACT_APP_SERVER_URL=${REACT_APP_SERVER_URL}
    volumes:
      - ./.nginx/:/etc/nginx/conf.d/:ro
